buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.bmuschko:gradle-docker-plugin:3.0.7'
		classpath 'org.ajoberstar:gradle-git:1.3.2'
	}
}

import nl.idgis.gradle.play.PlayJavaPlugin
import nl.idgis.gradle.docker.DockerPlugin


apply plugin: 'org.ajoberstar.release-opinion'

// Configure gradle-git release procedure (https://github.com/ajoberstar/gradle-git):
release {
	grgit = org.ajoberstar.grgit.Grgit.open (file ("."))
}

apply plugin: 'eclipse'
apply plugin: PlayJavaPlugin
apply plugin: DockerPlugin

ext {
	scalaAbiVersion = '2.11'
}

repositories {
	maven {
		url = "https://maven.pkg.github.com/IDgis/sysadmin"
		credentials {
			username = System.getenv("GITHUB_USER") ?: ghUser
			password = System.getenv("GITHUB_TOKEN") ?: ghKey
		}
	}
	maven {
		url = "https://maven.pkg.github.com/IDgis/idgis-commons"
		credentials {
			username = System.getenv("GITHUB_USER") ?: ghUser
			password = System.getenv("GITHUB_TOKEN") ?: ghKey
		}
	}
	ivy {
		name "typesafe-ivy-release"
		url "https://repo.typesafe.com/typesafe/ivy-releases"
		layout "ivy"
	}
	mavenCentral()
}

dependencies {
	// Play default dependencies (Scala version 2.11):
	play "com.typesafe.play:play-java-jdbc_2.11:2.4.3"			// javaJdbc
	play "com.typesafe.play:play-cache_2.11:2.4.3"				// cache
	play "com.typesafe.play:play-java-ws_2.11:2.4.3"			// javaWs
	play "com.typesafe.play:play-jdbc-evolutions_2.11:2.4.3"	// evolutions
	play "nl.idgis.commons:commons-utils:0.0.15"
	
	// Geoportaal dependencies:
	play "org.webjars:webjars-play_${scalaAbiVersion}:2.4.0-2"
	play "org.postgresql:postgresql:42.7.7"
	play ("nl.idgis.sys:provisioning-registration:1.1.6-SNAPSHOT") {
		exclude module: "ch.qos.logback"
		exclude module: "logback-classic"
	}
}
	
model {
	components {
		play {
			platform play: '2.4.3', java: '1.8'
			
			// The injected routes generator is required to be compatible with
			// Play version 2.4 and up. 
			injectedRoutesGenerator = true
		}
	}
}